In [2]:
import pandas as pd

In [3]:
customers= pd.read_csv('messy_customers.csv')

In [4]:
customers

    customer_id customer_name       city signup_date
0         C0001    Customer_1      DELHI  2024-02-09
1         C0002    Customer_2      delhi  2025-04-20
2         C0003    Customer_3  Bangalore  2024-08-19
3         C0004    Customer_4       Pune  2023-08-08
4         C0005           NaN  Bengaluru  2024-03-04
..          ...           ...        ...         ...
515       C0391  Customer_391    Kolkata  2023-01-07
516       C0483  Customer_483      Delhi  2023-02-25
517       C0473  Customer_473  Bangalore  2023-12-05
518       C0417  Customer_417  Bangalore  2025-01-24
519       C0303  Customer_303    Kolkata  2024-03-23

[520 rows x 4 columns]

In [5]:
orders= pd.read_csv('messy_orders.csv')

In [6]:
orders

     order_id customer_id  order_date    payment_method
0      O00001       C0058  09/05/2024  Cash on Delivery
1      O00002       C0410  2024-02-01               upi
2      O00003       C0429  13/04/2025              Cash
3      O00004       C0272  2024-02-25        Debit Card
4      O00005       C0411  04-26-2025       credit card
...       ...         ...         ...               ...
1235   O01078       C0222  03-15-2025  Cash on Delivery
1236   O00944       C0014  04-08-2024       credit card
1237   O00128       C0383  03-31-2025       Credit Card
1238   O00966       C0053  23/02/2024               upi
1239   O00313       C0428  12-21-2024  Cash on Delivery

[1240 rows x 4 columns]

In [7]:
products= pd.read_csv('messy_products.csv')

In [8]:
products

   product_id    product_name     category  base_price
0        P001  Lenovo IdeaPad       Tablet     28151.0
1        P002     Samsung Tab   Smartphone     68660.0
2        P003     HP Pavilion  Accessories         NaN
3        P004      Lenovo Tab       tablet         NaN
4        P005         OnePlus       Tablet         NaN
..        ...             ...          ...         ...
85       P022     Samsung Tab    Accessory         NaN
86       P052    Xiaomi Redmi  smart phone         NaN
87       P010       iPhone 13  smart phone         NaN
88       P059         OnePlus  Accessories         NaN
89       P033  Wireless Mouse       laptop     47453.0

[90 rows x 4 columns]

In [9]:
order_items= pd.read_csv('messy_order_items.csv')

In [10]:
order_items

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

working on MESSY_CUSTOMERS

In [11]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    520 non-null    object
 1   customer_name  492 non-null    object
 2   city           479 non-null    object
 3   signup_date    520 non-null    object
dtypes: object(4)
memory usage: 16.4+ KB

Assigning right Datatype(Especially datetime ,here)

In [12]:
customers['signup_date']=pd.to_datetime(customers['signup_date'])

In [13]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    520 non-null    object
 1   customer_name  492 non-null    object
 2   city           479 non-null    object
 3   signup_date    520 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 16.4+ KB

In [14]:
customers.describe()

                         signup_date
count                            520
mean   2024-03-05 20:10:09.230769408
min              2023-01-01 00:00:00
25%              2023-07-25 12:00:00
50%              2024-02-13 12:00:00
75%              2024-10-20 06:00:00
max              2025-06-19 00:00:00

In [15]:
customers.shape

(520, 4)

Handling DUPLICACY

In [16]:
customers.duplicated().sum()

np.int64(20)

In [17]:
customers.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
515     True
516     True
517     True
518     True
519     True
Length: 520, dtype: bool

In [18]:
customers.loc[customers.duplicated()]

    customer_id customer_name       city signup_date
500       C0309  Customer_309    Kolkata  2025-05-09
501       C0014   Customer_14      delhi  2024-08-18
502       C0415  Customer_415    Kolkata  2025-04-05
503       C0033   Customer_33     mumbai  2024-04-30
504       C0461  Customer_461    Chennai  2024-06-02
505       C0156  Customer_156       Pune  2024-08-07
506       C0250  Customer_250     Mumbai  2024-12-31
507       C0218  Customer_218      delhi  2025-02-02
508       C0222  Customer_222  Hyderabad  2024-05-20
509       C0294  Customer_294  Hyderabad  2023-09-12
510       C0133  Customer_133     Mumbai  2025-05-10
511       C0466  Customer_466     mumbai  2023-04-28
512       C0439  Customer_439  Hyderabad  2023-07-03
513       C0180  Customer_180        NaN  2025-01-16
514       C0498  Customer_498     Mumbai  2023-06-13
515       C0391  Customer_391    Kolkata  2023-01-07
516       C0483  Customer_483      Delhi  2023-02-25
517       C0473  Customer_473  Bangalore  2023-12-05
518       C0417  Customer_417  Bangalore  2025-01-24
519       C0303  Customer_303    Kolkata  2024-03-23

In [19]:
customers.drop_duplicates(inplace=True)

In [20]:
customers.loc[customers.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_name, city, signup_date]
Index: []

Handling NULL values

In [21]:
customers.isnull().sum()

customer_id       0
customer_name    28
city             40
signup_date       0
dtype: int64

In [22]:
customers[customers.isnull().any(axis=1)]

    customer_id customer_name       city signup_date
4         C0005           NaN  Bengaluru  2024-03-04
10        C0011           NaN      DELHI  2023-10-24
15        C0016   Customer_16        NaN  2023-03-06
27        C0028           NaN    Kolkata  2023-03-21
36        C0037   Customer_37        NaN  2024-01-31
..          ...           ...        ...         ...
470       C0471  Customer_471        NaN  2025-03-27
474       C0475  Customer_475        NaN  2023-02-19
477       C0478  Customer_478        NaN  2023-01-02
483       C0484           NaN  Bangalore  2023-11-08
496       C0497           NaN       Pune  2023-01-26

[66 rows x 4 columns]

In [23]:
customers['customer_name']=customers['customer_name'].replace({'NaN':'rajesh'})#(wrong as NaN is not a   string)

In [24]:
customers[customers.isnull().any(axis=1)]

    customer_id customer_name       city signup_date
4         C0005           NaN  Bengaluru  2024-03-04
10        C0011           NaN      DELHI  2023-10-24
15        C0016   Customer_16        NaN  2023-03-06
27        C0028           NaN    Kolkata  2023-03-21
36        C0037   Customer_37        NaN  2024-01-31
..          ...           ...        ...         ...
470       C0471  Customer_471        NaN  2025-03-27
474       C0475  Customer_475        NaN  2023-02-19
477       C0478  Customer_478        NaN  2023-01-02
483       C0484           NaN  Bangalore  2023-11-08
496       C0497           NaN       Pune  2023-01-26

[66 rows x 4 columns]

Using Function to fill Null Values

In [25]:
def fill():
    i=0
    while i<497:
        if pd.isna(customers.loc[i,'customer_name']):
            customers.loc[i,'customer_name']=f'customer_{i}'
        i+=1
fill()

In [26]:
customers[customers.isnull().any(axis=1)]

    customer_id customer_name city signup_date
15        C0016   Customer_16  NaN  2023-03-06
36        C0037   Customer_37  NaN  2024-01-31
71        C0072   Customer_72  NaN  2023-06-15
73        C0074   Customer_74  NaN  2024-07-10
83        C0084   Customer_84  NaN  2023-01-30
85        C0086   Customer_86  NaN  2024-09-11
97        C0098   Customer_98  NaN  2024-02-10
98        C0099   Customer_99  NaN  2023-03-28
105       C0106  Customer_106  NaN  2024-10-27
106       C0107  Customer_107  NaN  2023-05-23
119       C0120  Customer_120  NaN  2023-05-04
128       C0129  Customer_129  NaN  2023-10-11
145       C0146  Customer_146  NaN  2024-01-10
157       C0158  Customer_158  NaN  2023-07-07
179       C0180  Customer_180  NaN  2025-01-16
182       C0183  Customer_183  NaN  2025-06-19
201       C0202  Customer_202  NaN  2024-05-21
202       C0203  Customer_203  NaN  2024-09-25
205       C0206  Customer_206  NaN  2025-04-11
208       C0209  Customer_209  NaN  2024-11-30
250       C0251  customer_250  NaN  2023-10-24
279       C0280  Customer_280  NaN  2025-06-10
289       C0290  customer_289  NaN  2025-02-21
296       C0297  Customer_297  NaN  2024-12-18
311       C0312  Customer_312  NaN  2024-10-27
316       C0317  Customer_317  NaN  2023-12-13
333       C0334  Customer_334  NaN  2024-04-23
344       C0345  Customer_345  NaN  2024-04-30
352       C0353  Customer_353  NaN  2024-12-07
360       C0361  Customer_361  NaN  2023-11-07
370       C0371  Customer_371  NaN  2024-04-02
403       C0404  Customer_404  NaN  2023-10-05
408       C0409  Customer_409  NaN  2024-02-19
423       C0424  Customer_424  NaN  2024-09-27
430       C0431  Customer_431  NaN  2025-04-15
447       C0448  Customer_448  NaN  2023-11-18
468       C0469  Customer_469  NaN  2023-04-18
470       C0471  Customer_471  NaN  2025-03-27
474       C0475  Customer_475  NaN  2023-02-19
477       C0478  Customer_478  NaN  2023-01-02

In [27]:
customers.isnull().sum()

customer_id       0
customer_name     0
city             40
signup_date       0
dtype: int64

In [28]:
customers.drop(columns=['city'],inplace=True)
#Ran 2nd time so it shows error as city was already droped

In [29]:
customers.isnull().sum()

customer_id      0
customer_name    0
signup_date      0
dtype: int64

Handling INCONSISTENCY of data

In [30]:
customers['customer_name']=customers['customer_name'].str.title()

In [31]:
customers

    customer_id customer_name signup_date
0         C0001    Customer_1  2024-02-09
1         C0002    Customer_2  2025-04-20
2         C0003    Customer_3  2024-08-19
3         C0004    Customer_4  2023-08-08
4         C0005    Customer_4  2024-03-04
..          ...           ...         ...
495       C0496  Customer_496  2023-01-01
496       C0497  Customer_496  2023-01-26
497       C0498  Customer_498  2023-06-13
498       C0499  Customer_499  2023-01-13
499       C0500  Customer_500  2023-07-21

[500 rows x 3 columns]

In [32]:
customers.loc[customers.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_name, signup_date]
Index: []

Adding NEW COLUMN in dataframe by using function apply

In [33]:
def namcity(a):
    
    if a==f'{a}':
        return f"city_{a}"

In [34]:
customers['City']=customers['customer_name'].apply(namcity)

In [35]:
customers

    customer_id customer_name signup_date               City
0         C0001    Customer_1  2024-02-09    city_Customer_1
1         C0002    Customer_2  2025-04-20    city_Customer_2
2         C0003    Customer_3  2024-08-19    city_Customer_3
3         C0004    Customer_4  2023-08-08    city_Customer_4
4         C0005    Customer_4  2024-03-04    city_Customer_4
..          ...           ...         ...                ...
495       C0496  Customer_496  2023-01-01  city_Customer_496
496       C0497  Customer_496  2023-01-26  city_Customer_496
497       C0498  Customer_498  2023-06-13  city_Customer_498
498       C0499  Customer_499  2023-01-13  city_Customer_499
499       C0500  Customer_500  2023-07-21  city_Customer_500

[500 rows x 4 columns]

working on MESSY_ORDERS

In [36]:
orders

     order_id customer_id  order_date    payment_method
0      O00001       C0058  09/05/2024  Cash on Delivery
1      O00002       C0410  2024-02-01               upi
2      O00003       C0429  13/04/2025              Cash
3      O00004       C0272  2024-02-25        Debit Card
4      O00005       C0411  04-26-2025       credit card
...       ...         ...         ...               ...
1235   O01078       C0222  03-15-2025  Cash on Delivery
1236   O00944       C0014  04-08-2024       credit card
1237   O00128       C0383  03-31-2025       Credit Card
1238   O00966       C0053  23/02/2024               upi
1239   O00313       C0428  12-21-2024  Cash on Delivery

[1240 rows x 4 columns]

In [37]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1240 non-null   object
 1   customer_id     1240 non-null   object
 2   order_date      1240 non-null   object
 3   payment_method  1095 non-null   object
dtypes: object(4)
memory usage: 38.9+ KB

assigning right DATETIME datatype with mixed format

In [38]:
orders['order_date']=pd.to_datetime(orders['order_date'],format='mixed')

In [39]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1240 non-null   object
 1   customer_id     1240 non-null   object
 2   order_date      1240 non-null   datetime64[ns]
 3   payment_method  1095 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 38.9+ KB

In [40]:
orders.describe()

                          order_date
count                           1240
mean   2024-09-03 03:41:48.387096832
min              2024-01-01 00:00:00
25%              2024-04-24 00:00:00
50%              2024-08-24 00:00:00
75%              2025-01-05 12:00:00
max              2025-12-03 00:00:00

In [41]:
orders['payment_method']=orders['payment_method'].astype('str')

In [42]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1240 non-null   object
 1   customer_id     1240 non-null   object
 2   order_date      1240 non-null   datetime64[ns]
 3   payment_method  1240 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 38.9+ KB

DUPLICACY

In [43]:
orders.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1235     True
1236     True
1237     True
1238     True
1239     True
Length: 1240, dtype: bool

In [44]:
orders.loc[orders.duplicated()]

     order_id customer_id order_date    payment_method
1200   O00403       C0148 2024-10-28        Debit Card
1201   O00375       C0427 2024-07-03       credit card
1202   O00279       C0286 2024-12-06              Cash
1203   O00015       C0329 2024-02-09  Cash on Delivery
1204   O00147       C0303 2024-06-23       Credit Card
1205   O00186       C0333 2024-09-21              Cash
1206   O01084       C0186 2024-04-11              Cash
1207   O01188       C0094 2024-02-05               UPI
1208   O00350       C0328 2024-04-27       Credit Card
1209   O00526       C0068 2025-04-19              Cash
1210   O01122       C0084 2025-03-11       credit card
1211   O01152       C0104 2024-04-08               UPI
1212   O00681       C0313 2024-12-04  Cash on Delivery
1213   O00390       C0437 2025-04-10       credit card
1214   O01103       C0345 2024-03-22               nan
1215   O00195       C0125 2024-09-23  Cash on Delivery
1216   O00117       C0061 2025-04-07               UPI
1217   O01073       C0061 2025-01-12       Credit Card
1218   O00141       C0217 2024-10-13        Debit Card
1219   O00072       C0033 2024-01-06               UPI
1220   O01042       C0222 2024-05-10  Cash on Delivery
1221   O00288       C0253 2024-07-25       credit card
1222   O00351       C0379 2025-04-03       credit card
1223   O01124       C0298 2024-06-24       Credit Card
1224   O00413       C0340 2024-10-22  Cash on Delivery
1225   O00258       C0064 2024-11-28              Cash
1226   O00896       C0073 2024-05-27       Credit Card
1227   O00999       C0057 2024-06-25              Cash
1228   O00679       C0078 2024-09-20              Cash
1229   O00546       C0298 2024-12-11               UPI
1230   O00665       C0086 2024-06-30               nan
1231   O00863       C0218 2024-02-21               nan
1232   O00581       C0037 2024-05-20               nan
1233   O00144       C0100 2024-07-18  Cash on Delivery
1234   O00758       C0105 2024-06-24       Credit Card
1235   O01078       C0222 2025-03-15  Cash on Delivery
1236   O00944       C0014 2024-04-08       credit card
1237   O00128       C0383 2025-03-31       Credit Card
1238   O00966       C0053 2024-02-23               upi
1239   O00313       C0428 2024-12-21  Cash on Delivery

In [45]:
orders.duplicated().sum()

np.int64(40)

In [46]:
orders.drop_duplicates(inplace=True)

NULL values

In [47]:
orders[orders.isnull().any(axis=1)]

Empty DataFrame
Columns: [order_id, customer_id, order_date, payment_method]
Index: []

In [48]:
orders[orders['payment_method'].isna()]

Empty DataFrame
Columns: [order_id, customer_id, order_date, payment_method]
Index: []

In [49]:
orders['payment_method']=orders['payment_method'].replace({'nan':'Unknown'})

In [50]:
orders

     order_id customer_id order_date    payment_method
0      O00001       C0058 2024-09-05  Cash on Delivery
1      O00002       C0410 2024-02-01               upi
2      O00003       C0429 2025-04-13              Cash
3      O00004       C0272 2024-02-25        Debit Card
4      O00005       C0411 2025-04-26       credit card
...       ...         ...        ...               ...
1195   O01196       C0392 2024-09-14           Unknown
1196   O01197       C0260 2024-04-09           Unknown
1197   O01198       C0459 2024-05-29           Unknown
1198   O01199       C0130 2024-03-13           Unknown
1199   O01200       C0448 2024-03-06               UPI

[1200 rows x 4 columns]

INCONSISTENCY

In [51]:
orders['payment_method']=orders['payment_method'].str.title()

In [52]:
orders['payment_method']

0       Cash On Delivery
1                    Upi
2                   Cash
3             Debit Card
4            Credit Card
              ...
1195             Unknown
1196             Unknown
1197             Unknown
1198             Unknown
1199                 Upi
Name: payment_method, Length: 1200, dtype: object

Merging DataFrames

In [53]:
combined1=pd.merge(customers,orders,on='customer_id') # by default it applies inner join

In [54]:
combined1

,customer_id,customer_name,signup_date,City,order_id,order_date,payment_method
0,C0001,Customer_1,2024-02-09,city_Customer_1,O00309,2024-02-27,Debit Card
1,C0001,Customer_1,2024-02-09,city_Customer_1,O00541,2024-10-19,Upi
2,C0001,Customer_1,2024-02-09,city_Customer_1,O00675,2025-03-12,Upi
3,C0001,Customer_1,2024-02-09,city_Customer_1,O00782,2024-01-20,Upi
4,C0001,Customer_1,2024-02-09,city_Customer_1,O00987,2025-03-17,Cash
...,...,...,...,...,...,...,...
1195,C0497,Customer_496,2023-01-26,city_Customer_496,O00608,2024-05-23,Upi
1196,C0498,Customer_498,2023-06-13,city_Customer_498,O00448,2024-07-26,Cash
1197,C0498,Customer_498,2023-06-13,city_Customer_498,O00489,2025-11-01,Upi
1198,C0498,Customer_498,2023-06-13,city_Customer_498,O00789,2024-10-14,Upi
1199,C0498,Customer_498,2023-06-13,city_Customer_498,O01049,2024-08-30,Unknown

Exporting as csv and excel

In [55]:
combined1.to_csv('joined_data_messy.csv',index=False)

In [56]:
combined1.to_excel('result_messy.xlsx',sheet_name='merge_data_messy')

In [57]:
y = combined1.groupby("payment_method")['order_id'].count()

In [58]:
y

payment_method
Cash                163
Cash On Delivery    140
Credit Card         309
Debit Card          134
Unknown             141
Upi                 313
Name: order_id, dtype: int64

In [59]:
combined1['payment_method']=combined1['payment_method'].replace({'Cash':'Cash On Delivery'})

In [60]:
y = combined1.groupby("payment_method")['order_id'].count()

In [61]:
y

payment_method
Cash On Delivery    303
Credit Card         309
Debit Card          134
Unknown             141
Upi                 313
Name: order_id, dtype: int64

In [62]:
x=combined1.pivot_table("City",'payment_method','order_id','count')

In [63]:
x

order_id,O00001,O00002,O00003,O00004,O00005,O00006,O00007,O00008,O00009,O00010,...,O01191,O01192,O01193,O01194,O01195,O01196,O01197,O01198,O01199,O01200
payment_method,,,,,,,,,,,,,,,,,,,,,
Cash On Delivery,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Credit Card,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Debit Card,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN
Upi,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0

In [64]:
order_items

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

In [65]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  2050 non-null   int64
 1   order_id       2050 non-null   object
 2   product_id     2050 non-null   object
 3   quantity       1732 non-null   float64
 4   unit_price     1039 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 80.2+ KB

In [66]:
order_items.loc[order_items.duplicated()]

      order_item_id order_id product_id  quantity  unit_price
2000            689   O01021       P004       0.0         NaN
2001            436   O00386       P012       3.0     31320.0
2002           1596   O00176       P065       1.0         NaN
2003           1775   O00896       P030       3.0     40678.0
2004           1904   O00312       P031       3.0         NaN
2005           1420   O00327       P039       2.0     53326.0
2006            411   O01054       P072       0.0     85189.0
2007            697   O00355       P063       4.0     55126.0
2008           1006   O00750       P041       0.0         NaN
2009            861   O00205       P060       4.0     55826.0
2010           1532   O00015       P075       2.0     56095.0
2011            111   O01090       P018       0.0     41057.0
2012           1261   O00085       P046       0.0     76395.0
2013            746   O00155       P031       1.0         NaN
2014            360   O00523       P076       0.0     49730.0
2015            159   O00727       P002       1.0     34931.0
2016            988   O00612       P060       1.0     11160.0
2017            982   O00300       P068       0.0     53459.0
2018           1372   O01191       P076       2.0     89156.0
2019           1502   O00433       P018       0.0     40538.0
2020            306   O00354       P053       0.0         NaN
2021           1849   O01000       P059       2.0         NaN
2022            635   O00776       P062       1.0     16837.0
2023            549   O00681       P002       3.0     63663.0
2024           1203   O01008       P030       4.0         NaN
2025           1767   O00820       P042       4.0     35319.0
2026            546   O00636       P010       NaN         NaN
2027            197   O00301       P003       3.0     60818.0
2028            310   O01018       P050       1.0     39396.0
2029            594   O00372       P057       NaN         NaN
2030           1213   O00039       P052       1.0         NaN
2031            719   O00309       P029       4.0         NaN
2032            650   O00458       P040       NaN     17163.0
2033            276   O00571       P022       1.0     20373.0
2034           1772   O00900       P058       0.0         NaN
2035           1583   O00513       P035       4.0     33402.0
2036           1814   O00575       P080       0.0     80491.0
2037            716   O00473       P040       3.0     55590.0
2038           1805   O00977       P058       0.0         NaN
2039            156   O00621       P020       1.0         NaN
2040           1161   O01195       P020       0.0         NaN
2041           1316   O00686       P066       3.0         NaN
2042            997   O01103       P011       NaN     33021.0
2043           1601   O00843       P078       2.0         NaN
2044            999   O00921       P073       2.0         NaN
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

In [67]:
order_items.duplicated().sum()

np.int64(50)

In [68]:
order_items.drop_duplicates(inplace=True)

In [69]:
order_items.isna().sum()

order_item_id      0
order_id           0
product_id         0
quantity         313
unit_price       990
dtype: int64

In [70]:
order_items[order_items.isna().any(axis=1)]

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
5                 6   O00137       P023       1.0         NaN
6                 7   O00288       P070       0.0         NaN
8                 9   O00409       P015       1.0         NaN
...             ...      ...        ...       ...         ...
1991           1992   O00734       P026       2.0         NaN
1993           1994   O00899       P054       NaN     51205.0
1994           1995   O00364       P005       3.0         NaN
1996           1997   O00629       P017       4.0         NaN
1999           2000   O00596       P010       NaN     33991.0

[1155 rows x 5 columns]

In [71]:
order_items.isna().mean()*100

order_item_id     0.00
order_id          0.00
product_id        0.00
quantity         15.65
unit_price       49.50
dtype: float64

In [72]:
order_items.groupby('product_id')['unit_price'].agg(['count','min','max','median'])

            count      min      max   median
product_id
P001            8   5740.0  53114.0  32938.0
P002           15   1509.0  88990.0  59279.0
P003           11  10513.0  64992.0  40345.0
P004           13   3445.0  88764.0  26159.0
P005           10   8018.0  84879.0  37524.5
...           ...      ...      ...      ...
P076           29   6891.0  89156.0  58608.0
P077           12   3653.0  86726.0  36191.5
P078           11   6791.0  86702.0  46377.0
P079           14   3742.0  84451.0  53168.5
P080            9  24250.0  80491.0  56159.0

[80 rows x 4 columns]

In [73]:
price_map=order_items.groupby('product_id')['unit_price'].median()
order_items['unit_price']=order_items['unit_price'].fillna(order_items['product_id'].map(price_map))

In [74]:
order_items

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0     42539.0
1                 2   O00857       P010       1.0     38223.0
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
1995           1996   O00944       P007       4.0     64106.0
1996           1997   O00629       P017       4.0     54245.5
1997           1998   O00703       P008       0.0     76524.0
1998           1999   O01083       P043       3.0     18251.0
1999           2000   O00596       P010       NaN     33991.0

[2000 rows x 5 columns]

In [75]:
order_items['quantity'].describe()

count    1687.000000
mean        1.998814
std         1.409171
min         0.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         4.000000
Name: quantity, dtype: float64

In [76]:
order_items['quantity']=order_items['quantity'].fillna(order_items['quantity'].median())

In [77]:
order_items['quantity']

0       2.0
1       1.0
2       2.0
3       2.0
4       2.0
       ...
1995    4.0
1996    4.0
1997    0.0
1998    3.0
1999    2.0
Name: quantity, Length: 2000, dtype: float64

In [78]:
order_items

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0     42539.0
1                 2   O00857       P010       1.0     38223.0
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
1995           1996   O00944       P007       4.0     64106.0
1996           1997   O00629       P017       4.0     54245.5
1997           1998   O00703       P008       0.0     76524.0
1998           1999   O01083       P043       3.0     18251.0
1999           2000   O00596       P010       2.0     33991.0

[2000 rows x 5 columns]

In [79]:
products

   product_id    product_name     category  base_price
0        P001  Lenovo IdeaPad       Tablet     28151.0
1        P002     Samsung Tab   Smartphone     68660.0
2        P003     HP Pavilion  Accessories         NaN
3        P004      Lenovo Tab       tablet         NaN
4        P005         OnePlus       Tablet         NaN
..        ...             ...          ...         ...
85       P022     Samsung Tab    Accessory         NaN
86       P052    Xiaomi Redmi  smart phone         NaN
87       P010       iPhone 13  smart phone         NaN
88       P059         OnePlus  Accessories         NaN
89       P033  Wireless Mouse       laptop     47453.0

[90 rows x 4 columns]

In [80]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     object
 1   product_name  90 non-null     object
 2   category      90 non-null     object
 3   base_price    33 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.9+ KB

In [81]:
products.loc[products.duplicated()]

   product_id    product_name     category  base_price
80       P076  Wireless Mouse    Accessory     15249.0
81       P062   Dell Inspiron       Tablet         NaN
82       P072   Dell Inspiron       Tablet         NaN
83       P017        Keyboard   Smartphone         NaN
84       P020   Dell Inspiron   Smartphone         NaN
85       P022     Samsung Tab    Accessory         NaN
86       P052    Xiaomi Redmi  smart phone         NaN
87       P010       iPhone 13  smart phone         NaN
88       P059         OnePlus  Accessories         NaN
89       P033  Wireless Mouse       laptop     47453.0

In [82]:
products.duplicated().sum()

np.int64(10)

In [83]:
products.drop_duplicates(inplace=True)

In [84]:
products.isna().sum()

product_id       0
product_name     0
category         0
base_price      49
dtype: int64

In [85]:
products.groupby('product_id')['base_price'].agg(['count','min','max','mean'])

            count      min      max     mean
product_id
P001            1  28151.0  28151.0  28151.0
P002            1  68660.0  68660.0  68660.0
P003            0      NaN      NaN      NaN
P004            0      NaN      NaN      NaN
P005            0      NaN      NaN      NaN
...           ...      ...      ...      ...
P076            1  15249.0  15249.0  15249.0
P077            0      NaN      NaN      NaN
P078            1  70378.0  70378.0  70378.0
P079            0      NaN      NaN      NaN
P080            1  82478.0  82478.0  82478.0

[80 rows x 4 columns]

In [86]:
bprice_map=order_items.groupby('product_id')['unit_price'].mean()
products['base_price']=products['base_price'].fillna(products['product_id'].map(bprice_map))

In [87]:
products[products.isna().any(axis=1)]

Empty DataFrame
Columns: [product_id, product_name, category, base_price]
Index: []

In [88]:
products['product_name']=products['product_name'].str.title()

In [89]:
products

   product_id    product_name     category    base_price
0        P001  Lenovo Ideapad       Tablet  28151.000000
1        P002     Samsung Tab   Smartphone  68660.000000
2        P003     Hp Pavilion  Accessories  40489.000000
3        P004      Lenovo Tab       tablet  32011.400000
4        P005         Oneplus       Tablet  41247.388889
..        ...             ...          ...           ...
75       P076  Wireless Mouse    Accessory  15249.000000
76       P077  Wireless Mouse  smart phone  39614.833333
77       P078         Usb Hub    Accessory  70378.000000
78       P079         Oneplus       tablet  49850.653846
79       P080         Oneplus       laptop  82478.000000

[80 rows x 4 columns]

In [90]:
products['category']=products['category'].str.title()

In [91]:
products

   product_id    product_name     category    base_price
0        P001  Lenovo Ideapad       Tablet  28151.000000
1        P002     Samsung Tab   Smartphone  68660.000000
2        P003     Hp Pavilion  Accessories  40489.000000
3        P004      Lenovo Tab       Tablet  32011.400000
4        P005         Oneplus       Tablet  41247.388889
..        ...             ...          ...           ...
75       P076  Wireless Mouse    Accessory  15249.000000
76       P077  Wireless Mouse  Smart Phone  39614.833333
77       P078         Usb Hub    Accessory  70378.000000
78       P079         Oneplus       Tablet  49850.653846
79       P080         Oneplus       Laptop  82478.000000

[80 rows x 4 columns]

In [92]:
combined2=pd.merge(order_items,products,on='product_id')

In [93]:
combined2

,order_item_id,order_id,product_id,quantity,unit_price,product_name,category,base_price
0,1,O00380,P033,2.0,42539.0,Wireless Mouse,Laptop,47453.000000
1,2,O00857,P010,1.0,38223.0,Iphone 13,Smart Phone,41625.760870
2,3,O00589,P007,2.0,77415.0,Hp Pavilion,Accessories,57956.333333
3,4,O00112,P045,2.0,49066.0,Lenovo Tab,Laptop,50316.055556
4,5,O00322,P036,2.0,58380.0,Lenovo Ideapad,Tablet,40888.200000
...,...,...,...,...,...,...,...,...
1995,1996,O00944,P007,4.0,64106.0,Hp Pavilion,Accessories,57956.333333
1996,1997,O00629,P017,4.0,54245.5,Keyboard,Smartphone,53396.910256
1997,1998,O00703,P008,0.0,76524.0,Hp Pavilion,Accessory,38717.394737
1998,1999,O01083,P043,3.0,18251.0,Usb Hub,Accessory,35204.983871
1999,2000,O00596,P010,2.0,33991.0,Iphone 13,Smart Phone,41625.760870

In [94]:
combined1

,customer_id,customer_name,signup_date,City,order_id,order_date,payment_method
0,C0001,Customer_1,2024-02-09,city_Customer_1,O00309,2024-02-27,Debit Card
1,C0001,Customer_1,2024-02-09,city_Customer_1,O00541,2024-10-19,Upi
2,C0001,Customer_1,2024-02-09,city_Customer_1,O00675,2025-03-12,Upi
3,C0001,Customer_1,2024-02-09,city_Customer_1,O00782,2024-01-20,Upi
4,C0001,Customer_1,2024-02-09,city_Customer_1,O00987,2025-03-17,Cash On Delivery
...,...,...,...,...,...,...,...
1195,C0497,Customer_496,2023-01-26,city_Customer_496,O00608,2024-05-23,Upi
1196,C0498,Customer_498,2023-06-13,city_Customer_498,O00448,2024-07-26,Cash On Delivery
1197,C0498,Customer_498,2023-06-13,city_Customer_498,O00489,2025-11-01,Upi
1198,C0498,Customer_498,2023-06-13,city_Customer_498,O00789,2024-10-14,Upi
1199,C0498,Customer_498,2023-06-13,city_Customer_498,O01049,2024-08-30,Unknown

In [95]:
final_result=pd.merge(combined1,combined2,on='order_id')

In [96]:
final_result

,customer_id,customer_name,signup_date,City,order_id,order_date,payment_method,order_item_id,product_id,quantity,unit_price,product_name,category,base_price
0,C0001,Customer_1,2024-02-09,city_Customer_1,O00309,2024-02-27,Debit Card,124,P033,2.0,42539.0,Wireless Mouse,Laptop,47453.000000
1,C0001,Customer_1,2024-02-09,city_Customer_1,O00309,2024-02-27,Debit Card,235,P070,4.0,35845.0,Ipad Air,Tablet,33141.250000
2,C0001,Customer_1,2024-02-09,city_Customer_1,O00309,2024-02-27,Debit Card,397,P064,3.0,57795.5,Lenovo Ideapad,Accessories,81129.000000
3,C0001,Customer_1,2024-02-09,city_Customer_1,O00309,2024-02-27,Debit Card,719,P029,4.0,35095.5,Samsung Galaxy,Accessories,39583.260000
4,C0001,Customer_1,2024-02-09,city_Customer_1,O00309,2024-02-27,Debit Card,1206,P060,0.0,28975.0,Usb Hub,Laptop,31558.076923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,C0498,Customer_498,2023-06-13,city_Customer_498,O00489,2025-11-01,Upi,1488,P043,2.0,72197.0,Usb Hub,Accessory,35204.983871
1996,C0498,Customer_498,2023-06-13,city_Customer_498,O00789,2024-10-14,Upi,53,P028,4.0,41806.0,Samsung Galaxy,Tablet,35571.852941
1997,C0498,Customer_498,2023-06-13,city_Customer_498,O01049,2024-08-30,Unknown,256,P042,1.0,80536.0,Hp Pavilion,Laptop,36647.529412
1998,C0498,Customer_498,2023-06-13,city_Customer_498,O01049,2024-08-30,Unknown,1001,P072,1.0,16284.0,Dell Inspiron,Tablet,52421.127660
1999,C0498,Customer_498,2023-06-13,city_Customer_498,O01049,2024-08-30,Unknown,1297,P064,0.0,35441.0,Lenovo Ideapad,Accessories,81129.000000

In [97]:
final_result.to_csv('final_data_messy.csv',index=False)

In [98]:
final_result.to_excel('final_messy.xlsx',sheet_name="merged_data_messy")